name: All
on: [push]
jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            build-script: "build-dist.sh"
          - os: windows-latest
            name: windows
            build-script: "build-dist.ps1"
    steps:
      - name: Setup target name
        run: echo "target_name=dist-${{ matrix.name }}" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build
        run: "./${{ matrix.build-script }} ${{ env.target_name }}"
      - name: Zip release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ env.target_name }}.zip
          path: ${{ env.target_name }}/
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ env.target_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: True
          files: ${{ env.target_name }}.zip
